<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'cdli-user-profile/profile/index'           => __DIR__ . '/view/cdli-user-profile/profile/index.phtml',
    'cdli-user-profile/profile/section/zfcuser' => __DIR__ . '/view/cdli-user-profile/profile/section/zfcuser.phtml',
);
